name: DKBansReportRewardExtension
author: Davide Wietlisbach
description: 
version: ${project.version}
api-version: 1.13

main: ch.dkrieger.bansystem.extension.reportreward.bukkit.DKBansReportRewardExtension
commands:
