name: DKBansReportRewardExtension
author: Davide Wietlisbach
description: 
version: ${project.version}
api-version: 1.13
depend: [DKBans]

main: ch.dkrieger.bansystem.extension.consolecommand.bukkit.DKBansConsoleBanExtension
commands:
