name: DKBansMaintenanceModeExtension
author: Davide Wietlisbach
description: 
version: ${project.version}
api-version: 1.13
depend: [DKBans]

main: ch.dkrieger.bansystem.extension.maintenance.bukkit.DKBansMaintenanceExtension
commands:
