name: DKBansBanBroadcastExtension
author: Davide Wietlisbach
description: 
version: ${project.version}
api-version: 1.13

main: ch.dkrieger.bansystem.extension.banbroadcast.bukkit.DKBansBanBCExtension
commands:
