name: DKBansOfflinePermissionHook
author: Davide Wietlisbach
description: 
version: ${project.version}
api-version: 1.13
depend: [DKBans]
softdepend: [CloudNetAPI, LuckPerms]

main: ch.dkrieger.bansystem.extension.offlinepermissionhook.bukkit.DKBansOfflinePermissionHookExtension
commands:
