/*
 * (C) Copyright 2019 The DKBans Project (Davide Wietlisbach)
 *
 * @author Davide Wietlisbach
 * @since 08.11.19, 22:06
 * @Website https://github.com/DevKrieger/DKBans
 *
 * The DKBans Project is under the Apache License, version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

package ch.dkrieger.bansystem.lib.storage.sql.query;

import ch.dkrieger.bansystem.lib.storage.sql.MySQL;
import ch.dkrieger.bansystem.lib.storage.sql.SQL;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class ExecuteQuery extends Query {

    public ExecuteQuery(SQL sql, String query) {
        super(sql, query);
    }

    public void execute() {
        execute(0);
    }

    public Object execute(int autoGeneratedKeys) {
        this.endOptions.forEach((field, option)-> {
            this.query = query.substring(0,query.length()-1)+",";
            this.query += option+" ("+field+"))";
        });
        Connection connection = getConnection();
        try(final PreparedStatement preparedStatement = connection.prepareStatement(query, autoGeneratedKeys)) {
            int i = 1;
            for (Object object : values) {
                preparedStatement.setString(i, object.toString());
                i++;
            }
            preparedStatement.executeUpdate();
            if(autoGeneratedKeys != 0) {
                ResultSet result = preparedStatement.getGeneratedKeys();
                if(result != null){
                    if(result.next()) return result.getObject(1);
                }
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }finally {
            try {
                if(sql instanceof MySQL) connection.close();
            } catch (SQLException e) {}
        }
        return null;
    }
}